%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% noiseplot.m
% Author: M. Williams 2/10/12
% This file reads in data generated by our C++ project and outputs a graph
% based on figure 1 of McKane et al. It then does this in grayscale.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

filename = input('What is the filename for the data including extension?: ');
datamatrix = csvread(filename);

%We have now read in the data to the matrix datamatrix. Next we want to
%plot these. Going down in datamatrix (increasing rows) means a new
%discrete value of time. Going across in a row are all the heights in that
%time period.

i = 1; %counter for while expression

[rows, cols] = size(datamatrix); %rows is number of rows etc
hold on; %Ensure everything is plotted on one graph
plot(datamatrix(1,1),1)

%Now use two for loops to plot a graph. Note the commented out code is just
%debugging loops.
while i<=rows
    %fprintf('In outer loop. i is %6.2f.\n',i);
    j=1;
    while j<=cols
        %fprintf('In inner loop. j is %6.2f.\n',j);
        %fprintf('%6.2f.\n',datamatrix(i,j));
        plot(datamatrix(i,j), i, '-o');
        j=j+1;
    end
    i=i+1;
end
xlabel('Time');
ylabel('x');